CREATE TABLE scraped_books_raw (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255),
    price NUMBER,
    rating NUMBER,
    availability VARCHAR2(100),
    scraped_at DATE DEFAULT SYSDATE
);
