CREATE TABLE scraped_books_raw (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255),
    price NUMBER,
    rating NUMBER,
    availability VARCHAR2(100),
    category VARCHAR2(100),
    scraped_at DATE DEFAULT SYSDATE
);

CREATE TABLE dlq_books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload CLOB,
    error_message VARCHAR2(500),
    created_at DATE DEFAULT SYSDATE
);
