CREATE TABLE dim_book (
    sk VARCHAR2(64) PRIMARY KEY,
    title VARCHAR2(255)
);

CREATE TABLE fact_books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_sk VARCHAR2(64),
    category VARCHAR2(100),
    price NUMBER,
    rating NUMBER,
    source VARCHAR2(50),
    created_at DATE
);
